### PR TITLE
task-4 implementation

### PR DESCRIPTION
**Pull request by maksumov**
## Links

- App (FE) deploy: [https://dl0k87cgjwcxa.cloudfront.net/](https://dl0k87cgjwcxa.cloudfront.net/)
- App (FE) PR Url: [https://github.com/maksumov/nodejs-aws-fe/pull/3](https://github.com/maksumov/nodejs-aws-fe/pull/3)

**API endpoints (lambda links)**:

-  GET - [https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products](https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products)
-  GET - [https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products/{id}](https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products/{id})
-  POST - [https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products](https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products/{id})

**App URL for creating new products**:

- [https://dl0k87cgjwcxa.cloudfront.net/admin/product-form/](https://dl0k87cgjwcxa.cloudfront.net/admin/product-form/)

### Main tasks

- [x] Task 4.1 is implemented.
  - [DDL](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/sql/store.ddl.sql)
  - [DML](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/sql/store.dml.sql)
- [x] TASK 4.2 is implemented lambda links are provided and returns data
  - see API endpoints links above for confirmation.
- [x] TASK 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
  - Try to use POST /products endpoint through Postman or through [App URL for creating new products](https://dl0k87cgjwcxa.cloudfront.net/admin/product-form/)
  - New products can be checked through [GET /products endpoint](https://wnxy68e0x6.execute-api.eu-west-1.amazonaws.com/dev/products)
- [x] My own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.
  - Check App (FE) links above for confirmation.

Score for completing main tasks: 5/5.

### Additional tasks

- [x] POST/products lambda functions returns error 400 status code if product data is invalid.
  - API validates that sended product data match these requirements:
    - Data for create new product should contain title, description, price and count.
    - Price and count should be integers.
    - Title and description should be strings (text).
    - Price and count should be at least equal to 1.
- [x] All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
  - All lambdas contains `try` / `catch` blocks and return errot 500 in `catch` block. See sources for confimation: [1](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/getAllProducts.ts), [2](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/getProductById.ts), [3](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/createProduct.ts)
- [x] All lambdas do console.log for each incoming requests and their arguments
  - All lambdas logs `event` object at invocation. See sources for confimation: [1](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/getAllProducts.ts), [2](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/getProductById.ts), [3](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/createProduct.ts)
- [x] Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa)
  - Product creation is transaction-based, see [sources of the createProduct handler](https://github.com/maksumov/rss-shop-be/blob/task-4/product-service/handlers/createProduct.ts) for confirmation.

Score for completing additional tasks: 4/4.

### CODE REVIEW

**Comment by uladzimir-yeudakimovich** [comment]
image
need to check for a valid id

**Comment by maksumov** [comment]
> image
> need to check for a valid id

I have the corresponding code for checking invalid values. It just so happened that I was currently experimenting with the code

**Comment by maksumov** [comment]
image

**Comment by develjs** [comment]
it seems, FE part is not finished?
cases with listing products should be also fixed here:
https://dl0k87cgjwcxa.cloudfront.net/admin/products

**Comment by develjs** [comment]
The POST request returns "Invalid request body" with status=400 even from mentioned FE

**Comment by maksumov** [comment]
> it seems, FE part is not finished?
> cases with listing products should be also fixed here:
> https://dl0k87cgjwcxa.cloudfront.net/admin/products

Where is there a requirement to implement this functionality?

**Comment by maksumov** [comment]
> The POST request returns "Invalid request body" with status=400 even from mentioned FE

Show what you are sending in the body of the POST request, please. My requests are processed correctly and the product is being created.

**Comment by develjs** [comment]
> > it seems, FE part is not finished?
> > cases with listing products should be also fixed here:
> > https://dl0k87cgjwcxa.cloudfront.net/admin/products
> 
> Where is there a requirement to implement this functionality?
It's part of FE, and is covered by last requirement:
5 - Your own Frontend application is integrated with product service (/products API)...

**Comment by maksumov** [comment]
> > > it seems, FE part is not finished?
> > > cases with listing products should be also fixed here:
> > > https://dl0k87cgjwcxa.cloudfront.net/admin/products
> > 
> > 
> > Where is there a requirement to implement this functionality?
> > It's part of FE, and is covered by last requirement:
> > 5 - Your own Frontend application is integrated with product service (/products API)...

There is no requirements that my frontend app should be completed or requirements like 'cases with listing products should be also fixed here'. There is only ONE requirement: my FE app should be integrated with my API endpoints. And this requirement fullfilled:
- my FE app make GET request to /products endpoint for getting products;
- my FE app make POST request to /products endpoint for creating new product.

If you doubt that the requirement has been fullfilled please ask this with the course management.

**Comment by maksumov** [comment]
But thanks for pointing out what needs to be done to improve my FE app.

**Pull request merged**
